name: integration-test
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  integration-test-static:
    runs-on: macos-14
    if: >-
      github.event.issue.pull_request && (
        github.event.comment.body == '/integration-test' ||
        github.event.comment.body == '/integration-test static' ||
        github.event.comment.body == '/integration-test all'
      )
    steps:
      - name: Checkout PR
        uses: trinhngocthuyen/gh-actions/gh/pr/comment/checkout@main
        id: pr_checkout
      - name: Install languages
        uses: trinhngocthuyen/gh-actions/mono/install@main
        with:
          checkout: false
          ruby-version: '3.0'
      - name: Exec
        uses: trinhngocthuyen/gh-actions/gh/pr/with_check@main
        with:
          sha: ${{ steps.pr_checkout.outputs.head_sha }}
          exec: make ex.test.static

  integration-test-dynamic:
    runs-on: macos-14-large
    if: >-
      github.event.issue.pull_request && (
        github.event.comment.body == '/integration-test dynamic' ||
        github.event.comment.body == '/integration-test all'
      )
    steps:
      - name: Checkout PR
        uses: trinhngocthuyen/gh-actions/gh/pr/comment/checkout@main
        id: pr_checkout
      - name: Install languages
        uses: trinhngocthuyen/gh-actions/mono/install@main
        with:
          checkout: false
          ruby-version: '3.0'
      - name: Exec
        uses: trinhngocthuyen/gh-actions/gh/pr/with_check@main
        with:
          sha: ${{ steps.pr_checkout.outputs.head_sha }}
          exec: make ex.test.dynamic
